#!/bin/sh
PREREQ="a_enable_dhcpcd"
prereqs()
{
    echo "$PREREQ"
}

case $1 in
prereqs)
    prereqs
    exit 0
    ;;
esac

. /scripts/functions
export PATH='/sbin:/bin/:/usr/sbin:/usr/bin'

run_dropbear() {
    local flags="Fs"
    DROPBEAR_OPTIONS="-p 4748 -s -j -k -I 60"
    log_begin_msg "Starting dropbear"
    # using exec and keeping dropbear in the foreground enables the
    # init-bottom script to kill the remaining ipconfig processes if
    # someone unlocks the rootfs from the console while the network is
    # being configured
    exec /sbin/dropbear -$flags ${DROPBEAR_OPTIONS-}
}
run_dropbear &
echo $! >/run/dropbear.pid
