#!/bin/sh
PREREQ=""
prereqs()
{
    echo "$PREREQ"
}

case $1 in
prereqs)
    prereqs
    exit 0
    ;;
esac

. /scripts/functions
export PATH='/sbin:/bin/:/usr/sbin:/usr/bin'


# DHCPCD - run before wpa_supplicant ???
mkdir -p /var/run/dhcpcd
mkdir -p /var/lib/dhcpcd5
mkdir -p /var/run/sshd
mkdir -p /var/run/ssh
mkdir -p /run/sshd
mkdir -p /run/ssh
log_begin_msg "...running dhcpcd...."

/sbin/dhcpcd --nodev -w -L

echo -n "...dhcpcd should have started..."

#
# WIFI - WPA_SUPPLICANT
#

AUTH_LIMIT=30
INTERFACE="wlan0"
CTRL_SOCKET="/var/run/wpa_supplicant"
alias WPACLI="/sbin/wpa_cli -p$CTRL_SOCKET -i$INTERFACE"
mkdir -p /var/run/wpa_supplicant

# Wait for AUTH_LIMIT seconds, then check the status
limit=${AUTH_LIMIT}

echo -n "Waiting for connection (max ${AUTH_LIMIT} seconds)"
while [ $limit -ge 0 -a `WPACLI status | grep wpa_state` != "wpa_state=COMPLETED" ]
do
    sleep 1
    echo -n "."
    limit=`expr $limit - 1`
done
echo ""

if [ `WPACLI status | grep wpa_state` != "wpa_state=COMPLETED" ]; then
  ONLINE=0
  log_failure_msg "WLAN offline after timeout"
#  panic
else
  ONLINE=1
  log_success_msg "WLAN online"
fi

echo "`WPACLI status`"
echo "."
echo "`/sbin/ip addr`"
echo "."

#echo "Manually configureing network...\n"
#ipconfig -t 55 -c any wlan0
#configure_networking

#
# SSH server
#
mkdir -p /var/run/sshd
mkdir -p /run/sshd
log_begin_msg "...running sshd...."

/sbin/sshd -p 4748

echo -n "...sshd should have started..."

