#!/bin/sh
PREREQ=""
prereqs()
{
    echo "$PREREQ"
}

case $1 in
prereqs)
    prereqs
    exit 0
    ;;
esac

lockdir="/tmp/initram-locks"

#
# SSH
#
# killing it multiple ways - it really should be dead by the end of this
echo "Killing ssh..."
if [ -r /var/run/sshd.pid ]; then
	kill "`cat /var/run/sshd.pid`" > /dev/null 2>&1
	killall sshd > /dev/null 2>&1
fi

if [ -r "${lockdir}/sshd.pid" ]; then
        kill "`cat ${lockdir}/sshd.pid`" > /dev/null 2>&1
	killall sshd > /dev/null 2>&1
fi

killall sshd > /dev/null 2>&1
kill -9 `pgrep -f sshd` > /dev/null 2>&1

find /var/run/ -name '*sshd*' -exec rm -rf {} \; > /dev/null 2>&1
find /var/run/ -name '*ssh*' -exec rm -rf {} \; > /dev/null 2>&1
find /run/ -name '*sshd*' -exec rm -rf {} \; > /dev/null 2>&1
find /run/ -name '*ssh*' -exec rm -rf {} \; > /dev/null 2>&1
#
# WIFI
#
echo "Killing wpa_supplicant..."
killall wpa_supplicant > /dev/null 2>&1
kill -9 `pgrep -f wpa_supplicant` > /dev/null 2>&1
find /var/run/ -name '*wpa_supplicant*' -exec rm -rf {} \; > /dev/null 2>&1
find /run/ -name '*wpa_supplicant*' -exec rm -rf {} \; > /dev/null 2>&1
sleep 2

kill -9 `pgrep -f udhcpc` > /dev/null 2>&1

for i in $(ifconfig | grep -ve '^$' -e '^ ' -e '^lo ' | cut -d' ' -f1); do
	ifconfig "${i}" down
done

#blank resolvconf
echo " " > /etc/resolv.conf

#remove wifi module
modprobe -r brcmfmac

