#!/bin/sh
PREREQ=""
prereqs()
{
    echo "$PREREQ"
}

case $1 in
prereqs)
    prereqs
    exit 0
    ;;
esac

#
# SSH
#
echo "Killing ssh..."
if [ -r /var/run/sshd.pid ]; then
	kill "`cat /var/run/sshd.pid`"
	killall sshd >dev/null 2>&1
fi

#
# DHCPCD
#
echo "Killing dhcpcd..."
if [ -x /sbin/dhcpcd ] ; then
	echo `/sbin/ip addr`
	dhcpcd --exit
	killall dhcpcd
	for i in $(ifconfig | grep -ve '^$' -e '^ ' -e '^lo ' | cut -d' ' -f1); do
		ifconfig "${i}" down
	done
	echo `/sbin/ip addr`
	sleep 5
fi

#
# WIFI
#
echo "Killing wpa_supplicant..."
killall wpa_supplicant
